import "./globals.css";
import Header from "./components/Header";
import localFont from "next/font/local";

export const metadata = {
	title: "rurge",
	description: "Generated by create next app",
};

const poppins = localFont({
	src: [
		{
			path: "../public/fonts/bebasneueregular.woff2",
			weight: "400",
		},
		{
			path: "../public/fonts/bebasneueregular.woff2",
			weight: "700",
		},
	],
	variable: "--font-poppins",
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang='ru'
			/* className={bebas.className} */ className={`${poppins.variable} font-sans`}
		>
			<body>
				<Header />
				{children}
			</body>
		</html>
	);
}
